import ViewElement from './View';
import TextElement from './Text';
import TitleElement from './Title';
import SubtitleElement from './Subtitle';
import TagElement from './Tag';
import TimeLabelElement from './TimeLabel';
import CaptionElement from './Caption';
import DescriptionElement from './Description';
import ButtonElement from './Button';
import ArrowButtonElement from './ArrowButton';
import HeaderElement from './Header';

export const View = ViewElement;
export const Text = TextElement;
export const Title = TitleElement;
export const Subtitle = SubtitleElement;
export const Tag = TagElement;
export const TimeLabel = TimeLabelElement;
export const Caption = CaptionElement;
export const Description = DescriptionElement;
export const Button = ButtonElement;
export const ArrowButton = ArrowButtonElement;
export const Header = HeaderElement;
